//
//  HTMLReportTemplate.swift
//  SwiftLintRuleStudio
//
//  HTML/CSS template for the lint report
//

import Foundation

// swiftlint:disable function_body_length
extension HTMLReportGenerator {
    static func wrapInHTML(title: String, timestamp: String, body: String) -> String {
        """
        <!DOCTYPE html>
        <html lang="en">
        <head>
          <meta charset="utf-8">
          <meta name="viewport" content="width=device-width, initial-scale=1">
          <title>\(escapeHTML(title))</title>
          <style>
            :root {
              --bg: #ffffff; --fg: #1a1a1a; --muted: #666;
              --border: #e0e0e0; --card-bg: #f8f8f8;
              --error: #d32f2f; --error-bg: #fdecea;
              --warning: #f57c00; --warning-bg: #fff3e0;
              --green: #2e7d32; --blue: #1565c0;
            }
            @media (prefers-color-scheme: dark) {
              :root {
                --bg: #1e1e1e; --fg: #e0e0e0; --muted: #999;
                --border: #333; --card-bg: #2a2a2a;
                --error: #ef5350; --error-bg: #3e2723;
                --warning: #ffb74d; --warning-bg: #3e2723;
                --green: #66bb6a; --blue: #42a5f5;
              }
            }
            * { margin: 0; padding: 0; box-sizing: border-box; }
            body {
              font-family: -apple-system, BlinkMacSystemFont, 'SF Pro Text', sans-serif;
              background: var(--bg); color: var(--fg);
              max-width: 960px; margin: 0 auto; padding: 24px;
            }
            h1 { font-size: 24px; margin-bottom: 4px; }
            .timestamp { color: var(--muted); font-size: 13px; margin-bottom: 24px; }
            h2 { font-size: 18px; margin-bottom: 12px; border-bottom: 1px solid var(--border);
                 padding-bottom: 6px; }
            section { margin-bottom: 32px; }
            .cards { display: flex; gap: 12px; flex-wrap: wrap; }
            .card {
              flex: 1; min-width: 120px; padding: 16px;
              background: var(--card-bg); border-radius: 8px;
              border: 1px solid var(--border);
            }
            .card-value { font-size: 28px; font-weight: 700; }
            .card-label { font-size: 12px; color: var(--muted); margin-top: 4px; }
            .card-error .card-value { color: var(--error); }
            .card-warning .card-value { color: var(--warning); }
            .file-group { margin-bottom: 20px; }
            .file-group h3 { font-size: 15px; margin-bottom: 4px; }
            .file-count { font-weight: 400; color: var(--muted); font-size: 13px; margin-left: 8px; }
            .file-path { font-size: 11px; color: var(--muted); font-family: monospace;
                         margin-bottom: 8px; }
            table { width: 100%; border-collapse: collapse; font-size: 13px; }
            th { text-align: left; padding: 6px 8px; background: var(--card-bg);
                 border-bottom: 1px solid var(--border); font-weight: 600; }
            td { padding: 6px 8px; border-bottom: 1px solid var(--border); vertical-align: top; }
            .line-num { font-family: monospace; width: 50px; color: var(--muted); }
            .rule-id { font-family: monospace; white-space: nowrap; }
            .severity-error { color: var(--error); font-weight: 600; }
            .severity-warning { color: var(--warning); font-weight: 600; }
            .snippet-row td { padding: 0; }
            .snippet {
              font-family: 'SF Mono', Menlo, monospace; font-size: 12px;
              background: var(--card-bg); padding: 8px 12px; margin: 0;
              border-radius: 0; overflow-x: auto; white-space: pre;
            }
            .rule-detail { margin-bottom: 12px; padding: 12px; background: var(--card-bg);
                           border-radius: 8px; border: 1px solid var(--border); }
            .rule-detail h4 { font-size: 14px; font-family: monospace; }
            .rule-detail p { font-size: 13px; color: var(--muted); margin: 6px 0; }
            .rule-meta { font-size: 12px; color: var(--muted); }
            .rule-meta span { margin-right: 16px; }
            .footer { text-align: center; color: var(--muted); font-size: 11px;
                       margin-top: 40px; padding-top: 16px; border-top: 1px solid var(--border); }
          </style>
        </head>
        <body>
          <h1>\(escapeHTML(title))</h1>
          <p class="timestamp">Generated \(escapeHTML(timestamp))</p>
          \(body)
          <div class="footer">Generated by SwiftLint Rule Studio</div>
        </body>
        </html>
        """
    }
}
// swiftlint:enable function_body_length
