# SwiftLint Configuration for SwiftLint Rule Studio
# This configuration follows best practices for excluding third-party code
# and setting reasonable defaults for a macOS application.

# Exclude common build and dependency directories
excluded:
  - .build                    # Swift Package Manager dependencies
  - Pods                      # CocoaPods dependencies
  - .git                      # Git metadata
  - DerivedData               # Xcode build artifacts
  - .swiftpm                  # Swift Package Manager metadata
  - xcuserdata                # Xcode user-specific data
  - .xcode                    # Xcode project files
  - SwiftLIntRuleStudio.xcodeproj  # Xcode project bundle
  - SwiftLIntRuleStudioTests  # Unit/UI tests
  - SwiftLIntRuleStudioUITests  # UI tests

# Disable rules that are too strict for this project
disabled_rules:
  - todo                      # Allow TODO comments during development
  - trailing_newline          # Allow without strict enforcement
  - file_length               # Large views/services exceed limits
  - function_body_length      # Some helpers are intentionally long
  - type_body_length          # Several core types exceed limits

# Opt-in rules (enable specific rules that are valuable)
opt_in_rules:
  - empty_count               # Prefer isEmpty over count == 0
  - empty_string              # Prefer isEmpty over == ""
  - first_where               # Prefer first(where:) over filter.first
  - accessibility_trait_for_button  # SwiftUI: require button trait for tappable views
  - accessibility_label_for_image   # SwiftUI: require labels on images
  - force_unwrapping          # Warn about force unwraps
  - implicitly_unwrapped_optional  # Warn about IUOs
  - overridden_super_call     # Ensure super calls in overrides
  - prohibited_super_call    # Prevent incorrect super calls
  - redundant_nil_coalescing  # Remove redundant ?? nil
  - redundant_sendable        # Swift 6: Flag redundant Sendable conformances
  - single_test_class         # One test class per file
  - unneeded_parentheses_in_closure_argument  # Clean closure syntax
  - vertical_parameter_alignment_on_call  # Align parameters
  - incompatible_concurrency_annotation  # Swift 6: Flag incompatible concurrency annotations
  - async_without_await       # Swift 6: Flag async functions without await calls
  - unhandled_throwing_task   # Swift 6: Flag tasks where errors are not handled

# Custom rules
custom_rules:
  discarded_task:
    name: "Discarded Task"
    regex: 'let _ = Task\('
    message: "Use `_ = Task(...)` instead of `let _ = Task(...)` when discarding a task."
    severity: warning

# Rule configurations
trailing_whitespace:
  ignores_empty_lines: true

line_length:
  warning: 120
  error: 150
  ignores_function_declarations: true
  ignores_comments: true
  ignores_urls: true

function_parameter_count:
  warning: 5
  error: 8

identifier_name:
  min_length: 2
  excluded:
    - i
    - j
    - id

nesting:
  type_level: 2
  function_level: 3

# Reporter type (xcode, json, csv, checkstyle, junit, html, emoji, sonarqube, markdown)
reporter: "xcode"

