//
//  BuiltInTemplates.swift
//  SwiftLintRuleStudio
//
//  Static definitions for built-in configuration templates
//

import Foundation

// MARK: - Built-in Templates

/// Static definitions for built-in templates
enum BuiltInTemplates {
    /// Converts a known-valid UUID string literal into a UUID.
    /// Raises a precondition failure (not a crash in production) if the string is malformed.
    static func builtInID(_ string: String) -> UUID {
        guard let uuid = UUID(uuidString: string) else {
            preconditionFailure("Invalid built-in template UUID literal: \(string)")
        }
        return uuid
    }

    // MARK: - iOS App Templates

    static let iOSStrict = ConfigurationTemplate(
        id: builtInID("00000000-0000-0000-0000-000000000001"),
        name: "iOS App - Strict",
        description: "Maximum code quality for iOS applications",
        projectType: .iOSApp,
        codingStyle: .strict,
        yamlContent: """
        # SwiftLint Configuration - iOS App (Strict)
        # Generated by SwiftLint Rule Studio

        excluded:
          - Pods
          - Carthage
          - vendor
          - build
          - DerivedData
          - "*.generated.swift"

        opt_in_rules:
          - attributes
          - closure_end_indentation
          - closure_spacing
          - collection_alignment
          - contains_over_filter_count
          - contains_over_filter_is_empty
          - contains_over_first_not_nil
          - discouraged_object_literal
          - empty_collection_literal
          - empty_count
          - empty_string
          - enum_case_associated_values_count
          - explicit_init
          - first_where
          - flatmap_over_map_reduce
          - force_unwrapping
          - implicit_return
          - joined_default_parameter
          - last_where
          - modifier_order
          - multiline_arguments
          - multiline_parameters
          - operator_usage_whitespace
          - overridden_super_call
          - prefer_self_type_over_type_of_self
          - redundant_nil_coalescing
          - redundant_type_annotation
          - sorted_first_last
          - toggle_bool
          - trailing_closure
          - unneeded_parentheses_in_closure_argument
          - vertical_parameter_alignment_on_call
          - yoda_condition

        line_length:
          warning: 120
          error: 200
          ignores_urls: true
          ignores_function_declarations: false
          ignores_comments: true

        type_body_length:
          warning: 300
          error: 500

        file_length:
          warning: 500
          error: 1000
          ignore_comment_only_lines: true

        function_body_length:
          warning: 50
          error: 100

        cyclomatic_complexity:
          warning: 10
          error: 20

        nesting:
          type_level:
            warning: 2
            error: 3
          function_level:
            warning: 3
            error: 5
        """,
        isBuiltIn: true
    )

    static let iOSBalanced = ConfigurationTemplate(
        id: builtInID("00000000-0000-0000-0000-000000000002"),
        name: "iOS App - Balanced",
        description: "Good balance of quality and flexibility for iOS apps",
        projectType: .iOSApp,
        codingStyle: .balanced,
        yamlContent: """
        # SwiftLint Configuration - iOS App (Balanced)
        # Generated by SwiftLint Rule Studio

        excluded:
          - Pods
          - Carthage
          - vendor
          - build

        opt_in_rules:
          - empty_count
          - empty_string
          - first_where
          - last_where
          - modifier_order
          - sorted_first_last
          - contains_over_first_not_nil

        disabled_rules:
          - todo
          - trailing_whitespace

        line_length:
          warning: 140
          error: 250
          ignores_urls: true
          ignores_comments: true

        type_body_length:
          warning: 400
          error: 600

        file_length:
          warning: 600
          error: 1200

        function_body_length:
          warning: 60
          error: 150
        """,
        isBuiltIn: true
    )

    static let iOSLenient = ConfigurationTemplate(
        id: builtInID("00000000-0000-0000-0000-000000000003"),
        name: "iOS App - Lenient",
        description: "Minimal rules focused on critical issues",
        projectType: .iOSApp,
        codingStyle: .lenient,
        yamlContent: """
        # SwiftLint Configuration - iOS App (Lenient)
        # Generated by SwiftLint Rule Studio

        excluded:
          - Pods
          - Carthage

        disabled_rules:
          - line_length
          - file_length
          - type_body_length
          - function_body_length
          - cyclomatic_complexity
          - todo
          - trailing_whitespace
          - identifier_name
          - nesting

        force_cast: warning
        force_try: warning
        """,
        isBuiltIn: true
    )

    // MARK: - All Templates

    static var all: [ConfigurationTemplate] {
        [
            iOSStrict, iOSBalanced, iOSLenient,
            macOSStrict, macOSBalanced, macOSLenient,
            packageStrict, packageBalanced, packageLenient
        ]
    }
}
