//
//  BuiltInTemplates+macOS.swift
//  SwiftLintRuleStudio
//
//  Built-in macOS configuration templates
//

import Foundation

extension BuiltInTemplates {

    // MARK: - macOS App Templates

    static let macOSStrict = ConfigurationTemplate(
        id: builtInID("00000000-0000-0000-0000-000000000004"),
        name: "macOS App - Strict",
        description: "Maximum code quality for macOS applications",
        projectType: .macOSApp,
        codingStyle: .strict,
        yamlContent: """
        # SwiftLint Configuration - macOS App (Strict)
        # Generated by SwiftLint Rule Studio

        excluded:
          - Pods
          - Carthage
          - vendor
          - build
          - DerivedData

        opt_in_rules:
          - attributes
          - closure_end_indentation
          - closure_spacing
          - collection_alignment
          - contains_over_filter_count
          - empty_count
          - empty_string
          - explicit_init
          - first_where
          - force_unwrapping
          - implicit_return
          - last_where
          - modifier_order
          - overridden_super_call
          - redundant_nil_coalescing
          - sorted_first_last
          - trailing_closure
          - yoda_condition

        line_length:
          warning: 120
          error: 200
          ignores_urls: true

        type_body_length:
          warning: 300
          error: 500

        file_length:
          warning: 500
          error: 1000
        """,
        isBuiltIn: true
    )

    static let macOSBalanced = ConfigurationTemplate(
        id: builtInID("00000000-0000-0000-0000-000000000005"),
        name: "macOS App - Balanced",
        description: "Good balance for macOS applications",
        projectType: .macOSApp,
        codingStyle: .balanced,
        yamlContent: """
        # SwiftLint Configuration - macOS App (Balanced)
        # Generated by SwiftLint Rule Studio

        excluded:
          - Pods
          - Carthage
          - vendor

        opt_in_rules:
          - empty_count
          - first_where
          - last_where
          - modifier_order

        line_length:
          warning: 140
          error: 250
          ignores_urls: true
        """,
        isBuiltIn: true
    )

    static let macOSLenient = ConfigurationTemplate(
        id: builtInID("00000000-0000-0000-0000-000000000006"),
        name: "macOS App - Lenient",
        description: "Minimal rules for macOS applications",
        projectType: .macOSApp,
        codingStyle: .lenient,
        yamlContent: """
        # SwiftLint Configuration - macOS App (Lenient)
        # Generated by SwiftLint Rule Studio

        excluded:
          - Pods
          - Carthage

        disabled_rules:
          - line_length
          - file_length
          - todo
          - trailing_whitespace
        """,
        isBuiltIn: true
    )
}
