//
//  BuiltInTemplates+Package.swift
//  SwiftLintRuleStudio
//
//  Built-in Swift Package configuration templates
//

import Foundation

extension BuiltInTemplates {

    // MARK: - Swift Package Templates

    static let packageStrict = ConfigurationTemplate(
        id: builtInID("00000000-0000-0000-0000-000000000007"),
        name: "Swift Package - Strict",
        description: "Maximum code quality for Swift packages",
        projectType: .swiftPackage,
        codingStyle: .strict,
        yamlContent: """
        # SwiftLint Configuration - Swift Package (Strict)
        # Generated by SwiftLint Rule Studio

        excluded:
          - .build
          - Package.swift
          - Tests/LinuxMain.swift

        opt_in_rules:
          - attributes
          - closure_spacing
          - collection_alignment
          - contains_over_filter_count
          - empty_count
          - empty_string
          - explicit_init
          - first_where
          - force_unwrapping
          - implicit_return
          - last_where
          - missing_docs
          - modifier_order
          - redundant_nil_coalescing
          - sorted_first_last
          - yoda_condition

        line_length:
          warning: 120
          error: 200

        type_body_length:
          warning: 250
          error: 400

        file_length:
          warning: 400
          error: 800
        """,
        isBuiltIn: true
    )

    static let packageBalanced = ConfigurationTemplate(
        id: builtInID("00000000-0000-0000-0000-000000000008"),
        name: "Swift Package - Balanced",
        description: "Good balance for Swift packages",
        projectType: .swiftPackage,
        codingStyle: .balanced,
        yamlContent: """
        # SwiftLint Configuration - Swift Package (Balanced)
        # Generated by SwiftLint Rule Studio

        excluded:
          - .build
          - Package.swift

        opt_in_rules:
          - empty_count
          - first_where
          - last_where

        line_length:
          warning: 140
          error: 250
        """,
        isBuiltIn: true
    )

    static let packageLenient = ConfigurationTemplate(
        id: builtInID("00000000-0000-0000-0000-000000000009"),
        name: "Swift Package - Lenient",
        description: "Minimal rules for Swift packages",
        projectType: .swiftPackage,
        codingStyle: .lenient,
        yamlContent: """
        # SwiftLint Configuration - Swift Package (Lenient)
        # Generated by SwiftLint Rule Studio

        excluded:
          - .build

        disabled_rules:
          - line_length
          - todo
        """,
        isBuiltIn: true
    )
}
