//
//  PRCommentGenerator.swift
//  SwiftLintRuleStudio
//
//  Generates markdown PR comments from configuration diffs
//

import Foundation
import AppKit

/// Protocol for generating PR comments from configuration diffs
@MainActor
protocol PRCommentGeneratorProtocol {
    /// Generate markdown from a configuration diff
    func generateMarkdown(from diff: YAMLConfigurationEngine.ConfigDiff) -> String

    /// Generate markdown with custom options
    func generateMarkdown(
        from diff: YAMLConfigurationEngine.ConfigDiff,
        options: PRCommentOptions
    ) -> String

    /// Copy the generated markdown to the clipboard
    func copyToClipboard(_ markdown: String)
}

/// Options for customizing PR comment generation
struct PRCommentOptions: Sendable {
    let includeHeader: Bool
    let includeFooter: Bool
    let includeRuleLinks: Bool
    let includeDiffSummary: Bool
    let customTitle: String?

    init(
        includeHeader: Bool = true,
        includeFooter: Bool = true,
        includeRuleLinks: Bool = true,
        includeDiffSummary: Bool = true,
        customTitle: String? = nil
    ) {
        self.includeHeader = includeHeader
        self.includeFooter = includeFooter
        self.includeRuleLinks = includeRuleLinks
        self.includeDiffSummary = includeDiffSummary
        self.customTitle = customTitle
    }

    static var `default`: PRCommentOptions {
        PRCommentOptions()
    }

    static var minimal: PRCommentOptions {
        PRCommentOptions(
            includeHeader: false,
            includeFooter: false,
            includeRuleLinks: false,
            includeDiffSummary: false
        )
    }
}

/// Service for generating markdown PR comments from configuration changes
@MainActor
class PRCommentGenerator: PRCommentGeneratorProtocol {
    private let swiftLintDocsBaseURL = "https://realm.github.io/SwiftLint"

    func generateMarkdown(from diff: YAMLConfigurationEngine.ConfigDiff) -> String {
        generateMarkdown(from: diff, options: .default)
    }

    func generateMarkdown(
        from diff: YAMLConfigurationEngine.ConfigDiff,
        options: PRCommentOptions
    ) -> String {
        var lines: [String] = []

        // Header
        if options.includeHeader {
            let title = options.customTitle ?? "SwiftLint Configuration Changes"
            lines.append("## \(title)")
            lines.append("")
        }

        // Summary section
        if options.includeDiffSummary {
            lines.append(contentsOf: generateSummarySection(from: diff))
        }

        // Added rules section
        if !diff.addedRules.isEmpty {
            lines.append(contentsOf: generateRulesSection(
                title: "Rules Added",
                emoji: "+",
                rules: diff.addedRules,
                includeLinks: options.includeRuleLinks
            ))
        }

        // Removed rules section
        if !diff.removedRules.isEmpty {
            lines.append(contentsOf: generateRulesSection(
                title: "Rules Removed",
                emoji: "-",
                rules: diff.removedRules,
                includeLinks: options.includeRuleLinks
            ))
        }

        // Modified rules section
        if !diff.modifiedRules.isEmpty {
            lines.append(contentsOf: generateRulesSection(
                title: "Rules Modified",
                emoji: "~",
                rules: diff.modifiedRules,
                includeLinks: options.includeRuleLinks
            ))
        }

        // No changes case
        if !diff.hasChanges {
            lines.append("*No changes to SwiftLint configuration.*")
            lines.append("")
        }

        // Footer
        if options.includeFooter {
            lines.append("---")
            lines.append("*Generated by SwiftLint Rule Studio*")
        }

        return lines.joined(separator: "\n")
    }

    func copyToClipboard(_ markdown: String) {
        let pasteboard = NSPasteboard.general
        pasteboard.clearContents()
        pasteboard.setString(markdown, forType: .string)
    }

    // MARK: - Private Methods

    private func generateSummarySection(
        from diff: YAMLConfigurationEngine.ConfigDiff
    ) -> [String] {
        var lines: [String] = []

        let totalChanges = diff.addedRules.count + diff.removedRules.count + diff.modifiedRules.count

        if totalChanges > 0 {
            lines.append("### Summary")
            lines.append("")

            if !diff.addedRules.isEmpty {
                lines.append("- **\(diff.addedRules.count)** rule(s) added")
            }
            if !diff.removedRules.isEmpty {
                lines.append("- **\(diff.removedRules.count)** rule(s) removed")
            }
            if !diff.modifiedRules.isEmpty {
                lines.append("- **\(diff.modifiedRules.count)** rule(s) modified")
            }

            lines.append("")
        }

        return lines
    }

    private func generateRulesSection(
        title: String,
        emoji: String,
        rules: [String],
        includeLinks: Bool
    ) -> [String] {
        var lines: [String] = []

        lines.append("### \(title) (\(rules.count))")
        lines.append("")

        for rule in rules.sorted() {
            if includeLinks {
                let ruleURL = "\(swiftLintDocsBaseURL)/\(rule).html"
                lines.append("- [\(emoji)] [`\(rule)`](\(ruleURL))")
            } else {
                lines.append("- [\(emoji)] `\(rule)`")
            }
        }

        lines.append("")

        return lines
    }
}

// MARK: - Convenience Extensions

extension YAMLConfigurationEngine.ConfigDiff {
    /// Generate a markdown PR comment from this diff
    @MainActor
    func toMarkdown(options: PRCommentOptions = .default) -> String {
        let generator = PRCommentGenerator()
        return generator.generateMarkdown(from: self, options: options)
    }
}
