//
//  ExportFormatTests.swift
//  SwiftLintRuleStudioTests
//
//  Tests for ExportFormat enum and HTMLReportTemplate
//

import Testing
import Foundation
@testable import SwiftLintRuleStudio

@MainActor
@Suite("ExportFormat Tests")
struct ExportFormatTests {

    @Test("ExportFormat has three cases")
    func allCases() {
        #expect(ExportFormat.allCases.count == 3)
        #expect(ExportFormat.allCases.contains(.html))
        #expect(ExportFormat.allCases.contains(.json))
        #expect(ExportFormat.allCases.contains(.csv))
    }

    @Test("ExportFormat rawValues are correct")
    func rawValues() {
        #expect(ExportFormat.html.rawValue == "HTML")
        #expect(ExportFormat.json.rawValue == "JSON")
        #expect(ExportFormat.csv.rawValue == "CSV")
    }

    @Test("ExportFormat id matches rawValue")
    func identifiers() {
        for format in ExportFormat.allCases {
            #expect(format.id == format.rawValue)
        }
    }

    @Test("ExportFormat subtitles are descriptive")
    func subtitles() {
        #expect(ExportFormat.html.subtitle == "Interactive report")
        #expect(ExportFormat.json.subtitle == "Machine-readable")
        #expect(ExportFormat.csv.subtitle == "Spreadsheet")
    }

    @Test("ExportFormat iconNames are valid SF Symbol names")
    func iconNames() {
        #expect(ExportFormat.html.iconName == "doc.richtext")
        #expect(ExportFormat.json.iconName == "curlybraces")
        #expect(ExportFormat.csv.iconName == "tablecells")
    }

    @Test("ExportFormat fileExtensions are lowercase versions of rawValue")
    func fileExtensions() {
        #expect(ExportFormat.html.fileExtension == "html")
        #expect(ExportFormat.json.fileExtension == "json")
        #expect(ExportFormat.csv.fileExtension == "csv")
    }
}

@MainActor
@Suite("HTMLReportTemplate Tests")
struct HTMLReportTemplateTests {

    @Test("wrapInHTML produces valid HTML document")
    func validDocument() {
        let html = HTMLReportGenerator.wrapInHTML(
            title: "Test Report",
            timestamp: "2026-01-01",
            body: "<p>Hello</p>"
        )

        #expect(html.contains("<!DOCTYPE html>"))
        #expect(html.contains("<title>Test Report</title>"))
        #expect(html.contains("2026-01-01"))
        #expect(html.contains("<p>Hello</p>"))
    }

    @Test("wrapInHTML escapes title for HTML safety")
    func escapesTitle() {
        let html = HTMLReportGenerator.wrapInHTML(
            title: "Test <script>alert(1)</script>",
            timestamp: "now",
            body: ""
        )

        #expect(html.contains("&lt;script&gt;"))
        #expect(!html.contains("<script>alert(1)</script>"))
    }

    @Test("wrapInHTML includes responsive meta tag")
    func responsiveMeta() {
        let html = HTMLReportGenerator.wrapInHTML(
            title: "Test",
            timestamp: "now",
            body: ""
        )

        #expect(html.contains("viewport"))
    }

    @Test("wrapInHTML includes embedded CSS with dark mode")
    func embeddedCSS() {
        let html = HTMLReportGenerator.wrapInHTML(
            title: "Test",
            timestamp: "now",
            body: ""
        )

        #expect(html.contains("<style>"))
        #expect(html.contains("prefers-color-scheme: dark"))
        #expect(html.contains("--bg:"))
        #expect(html.contains("--fg:"))
    }

    @Test("wrapInHTML includes footer branding")
    func footerBranding() {
        let html = HTMLReportGenerator.wrapInHTML(
            title: "Test",
            timestamp: "now",
            body: ""
        )

        #expect(html.contains("Generated by SwiftLint Rule Studio"))
    }
}
