//
//  HTMLReportGeneratorTests.swift
//  SwiftLintRuleStudioTests
//
//  Tests for HTML report generation
//

import Testing
import Foundation
@testable import SwiftLintRuleStudioCore
import SwiftLintRuleStudioCoreTestSupport
@testable import SwiftLintRuleStudio

@MainActor
@Suite("HTMLReportGenerator Tests")
struct HTMLReportGeneratorTests {

    // MARK: - Test Helpers

    private func makeViolation(
        ruleID: String = "line_length",
        filePath: String = "/path/to/File.swift",
        line: Int = 42,
        column: Int? = nil,
        severity: Severity = .warning,
        message: String = "Line too long"
    ) -> Violation {
        Violation(
            ruleID: ruleID,
            filePath: filePath,
            line: line,
            column: column,
            severity: severity,
            message: message,
            detectedAt: Date(timeIntervalSince1970: 1_000_000)
        )
    }

    private func makeOptions(
        violations: [Violation] = [],
        workspaceName: String = "TestProject",
        includeSummary: Bool = true,
        includeDetailedList: Bool = true,
        includeCodeSnippets: Bool = false,
        includeRuleConfig: Bool = false
    ) -> HTMLReportOptions {
        let cacheManager = CacheManager.createForTesting()
        let swiftLintCLI = SwiftLintCLIActor(cacheManager: cacheManager)
        let registry = RuleRegistry(
            swiftLintCLI: swiftLintCLI,
            cacheManager: cacheManager
        )
        return HTMLReportOptions(
            violations: violations,
            workspaceName: workspaceName,
            includeSummary: includeSummary,
            includeDetailedList: includeDetailedList,
            includeCodeSnippets: includeCodeSnippets,
            includeRuleConfig: includeRuleConfig,
            ruleRegistry: registry
        )
    }

    // MARK: - HTML Structure Tests

    @Test("Generated HTML has valid document structure")
    func validHTMLStructure() {
        let options = makeOptions()
        let html = HTMLReportGenerator.generate(options: options)

        #expect(html.contains("<!DOCTYPE html>"))
        #expect(html.contains("<html lang=\"en\">"))
        #expect(html.contains("</html>"))
        #expect(html.contains("<head>"))
        #expect(html.contains("</head>"))
        #expect(html.contains("<body>"))
        #expect(html.contains("</body>"))
    }

    @Test("HTML includes workspace name in title")
    func includesWorkspaceName() {
        let options = makeOptions(workspaceName: "MyAwesomeProject")
        let html = HTMLReportGenerator.generate(options: options)

        #expect(html.contains("MyAwesomeProject"))
        #expect(html.contains("<title>MyAwesomeProject"))
    }

    @Test("HTML includes timestamp")
    func includesTimestamp() {
        let options = makeOptions()
        let html = HTMLReportGenerator.generate(options: options)

        #expect(html.contains("Generated"))
        #expect(html.contains("class=\"timestamp\""))
    }

    @Test("HTML includes footer")
    func includesFooter() {
        let options = makeOptions()
        let html = HTMLReportGenerator.generate(options: options)

        #expect(html.contains("Generated by SwiftLint Rule Studio"))
    }

    // MARK: - Summary Section Tests

    @Test("Summary section shows correct violation counts")
    func summaryShowsCounts() {
        let violations = [
            makeViolation(severity: .error),
            makeViolation(severity: .warning),
            makeViolation(severity: .warning)
        ]
        let options = makeOptions(violations: violations, includeSummary: true)
        let html = HTMLReportGenerator.generate(options: options)

        #expect(html.contains("Summary"))
        #expect(html.contains("Total Violations"))
        #expect(html.contains("Errors"))
        #expect(html.contains("Warnings"))
    }

    @Test("Summary section omitted when includeSummary is false")
    func summaryOmittedWhenDisabled() {
        let violations = [makeViolation()]
        let options = makeOptions(violations: violations, includeSummary: false, includeDetailedList: false)
        let html = HTMLReportGenerator.generate(options: options)

        #expect(!html.contains("class=\"summary\""))
        #expect(!html.contains("Total Violations"))
    }

    // MARK: - Detailed List Section Tests

    @Test("Detailed list groups violations by file")
    func detailedListGroupsByFile() {
        let violations = [
            makeViolation(filePath: "/src/Alpha.swift", line: 10),
            makeViolation(filePath: "/src/Alpha.swift", line: 20),
            makeViolation(filePath: "/src/Beta.swift", line: 5)
        ]
        let options = makeOptions(violations: violations, includeDetailedList: true)
        let html = HTMLReportGenerator.generate(options: options)

        #expect(html.contains("Alpha.swift"))
        #expect(html.contains("Beta.swift"))
        #expect(html.contains("Violations by File"))
    }

    @Test("Detailed list shows severity styling")
    func detailedListShowsSeverity() {
        let violations = [
            makeViolation(severity: .error),
            makeViolation(line: 50, severity: .warning)
        ]
        let options = makeOptions(violations: violations, includeDetailedList: true)
        let html = HTMLReportGenerator.generate(options: options)

        #expect(html.contains("severity-error"))
        #expect(html.contains("severity-warning"))
        #expect(html.contains("Error"))
        #expect(html.contains("Warning"))
    }

    @Test("Detailed list omitted when includeDetailedList is false")
    func detailedListOmittedWhenDisabled() {
        let violations = [makeViolation()]
        let options = makeOptions(violations: violations, includeSummary: false, includeDetailedList: false)
        let html = HTMLReportGenerator.generate(options: options)

        #expect(!html.contains("class=\"details\""))
        #expect(!html.contains("Violations by File"))
    }

    @Test("Detailed list sorts violations by line number within file")
    func detailedListSortsByLine() {
        let violations = [
            makeViolation(line: 99, message: "Late violation"),
            makeViolation(line: 5, message: "Early violation"),
            makeViolation(line: 42, message: "Middle violation")
        ]
        let options = makeOptions(violations: violations, includeDetailedList: true)
        let html = HTMLReportGenerator.generate(options: options)

        // All violations from same file should appear; check they exist
        #expect(html.contains("Late violation"))
        #expect(html.contains("Early violation"))
        #expect(html.contains("Middle violation"))

        // Check line number order: 5 should appear before 42 should appear before 99
        if let pos5 = html.range(of: "Early violation"),
           let pos42 = html.range(of: "Middle violation"),
           let pos99 = html.range(of: "Late violation") {
            #expect(pos5.lowerBound < pos42.lowerBound)
            #expect(pos42.lowerBound < pos99.lowerBound)
        }
    }

    // MARK: - Rule Config Section Tests

    @Test("Rule config section shows rule details")
    func ruleConfigShowsDetails() {
        let violations = [
            makeViolation(ruleID: "force_cast"),
            makeViolation(ruleID: "force_cast"),
            makeViolation(ruleID: "line_length")
        ]
        let cacheManager = CacheManager.createForTesting()
        let swiftLintCLI = SwiftLintCLIActor(cacheManager: cacheManager)
        let registry = RuleRegistry(
            swiftLintCLI: swiftLintCLI,
            cacheManager: cacheManager
        )
        // Add a rule for lookup
        registry.setRulesForTesting([
            Rule(
                id: "force_cast",
                name: "Force Cast",
                description: "Force casts should be avoided",
                category: .lint,
                isOptIn: false,
                supportsAutocorrection: false
            )
        ])

        let options = HTMLReportOptions(
            violations: violations,
            workspaceName: "TestProject",
            includeSummary: false,
            includeDetailedList: false,
            includeCodeSnippets: false,
            includeRuleConfig: true,
            ruleRegistry: registry
        )

        let html = HTMLReportGenerator.generate(options: options)

        #expect(html.contains("Rule Details"))
        #expect(html.contains("force_cast"))
        #expect(html.contains("Force casts should be avoided"))
        #expect(html.contains("2 violations")) // force_cast appears twice
        #expect(html.contains("line_length"))
    }

    @Test("Rule config section omitted when includeRuleConfig is false")
    func ruleConfigOmittedWhenDisabled() {
        let violations = [makeViolation()]
        let options = makeOptions(
            violations: violations,
            includeSummary: false,
            includeDetailedList: false,
            includeRuleConfig: false
        )
        let html = HTMLReportGenerator.generate(options: options)

        #expect(!html.contains("class=\"rule-config\""))
        #expect(!html.contains("Rule Details"))
    }

}

// MARK: - HTML Escaping & Edge Case Tests

@MainActor
@Suite("HTMLReportGenerator Escaping Tests")
struct HTMLReportGeneratorEscapingTests {

    @Test("escapeHTML escapes ampersands")
    func escapesAmpersands() {
        let result = HTMLReportGenerator.escapeHTML("A & B")
        #expect(result == "A &amp; B")
    }

    @Test("escapeHTML escapes angle brackets")
    func escapesAngleBrackets() {
        let result = HTMLReportGenerator.escapeHTML("<script>alert('xss')</script>")
        #expect(result == "&lt;script&gt;alert('xss')&lt;/script&gt;")
    }

    @Test("escapeHTML escapes double quotes")
    func escapesDoubleQuotes() {
        let result = HTMLReportGenerator.escapeHTML("She said \"hello\"")
        #expect(result == "She said &quot;hello&quot;")
    }

    @Test("escapeHTML handles multiple special characters together")
    func escapesMultipleSpecials() {
        let result = HTMLReportGenerator.escapeHTML("<a href=\"/test?a=1&b=2\">")
        #expect(result == "&lt;a href=&quot;/test?a=1&amp;b=2&quot;&gt;")
    }

    @Test("escapeHTML passes through safe strings unchanged")
    func safeStringsUnchanged() {
        let safeText = "Hello World 123"
        let result = HTMLReportGenerator.escapeHTML(safeText)
        #expect(result == safeText)
    }

    @Test("HTML includes embedded CSS styles")
    func includesCSS() {
        let html = HTMLReportGenerator.generate(
            options: HTMLReportOptions(
                violations: [],
                workspaceName: "Test",
                includeSummary: false,
                includeDetailedList: false,
                includeCodeSnippets: false,
                includeRuleConfig: false,
                ruleRegistry: RuleRegistry(
                    swiftLintCLI: SwiftLintCLIActor(
                        cacheManager: CacheManager.createForTesting()
                    ),
                    cacheManager: CacheManager.createForTesting()
                )
            )
        )

        #expect(html.contains("<style>"))
        #expect(html.contains("</style>"))
        #expect(html.contains("font-family"))
    }

    @Test("HTML includes dark mode CSS support")
    func includesDarkModeCSS() {
        let html = HTMLReportGenerator.generate(
            options: HTMLReportOptions(
                violations: [],
                workspaceName: "Test",
                includeSummary: false,
                includeDetailedList: false,
                includeCodeSnippets: false,
                includeRuleConfig: false,
                ruleRegistry: RuleRegistry(
                    swiftLintCLI: SwiftLintCLIActor(
                        cacheManager: CacheManager.createForTesting()
                    ),
                    cacheManager: CacheManager.createForTesting()
                )
            )
        )

        #expect(html.contains("prefers-color-scheme: dark"))
    }
}
