//
//  PRCommentGeneratorTests.swift
//  SwiftLintRuleStudioTests
//
//  Unit tests for PRCommentGenerator
//

import Foundation
import Testing
@testable import SwiftLIntRuleStudio

@MainActor
struct PRCommentGeneratorTests {
    // MARK: - Basic Generation Tests

    @Test("Generates markdown with added rules")
    func testGeneratesMarkdownWithAddedRules() async {
        let generator = PRCommentGenerator()
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: ["force_cast", "line_length"],
            removedRules: [],
            modifiedRules: [],
            before: "",
            after: ""
        )
        let markdown = generator.generateMarkdown(from: diff)

        #expect(markdown.contains("## SwiftLint Configuration Changes"))
        #expect(markdown.contains("### Rules Added (2)"))
        #expect(markdown.contains("`force_cast`"))
        #expect(markdown.contains("`line_length`"))
        #expect(markdown.contains("Generated by SwiftLint Rule Studio"))
    }

    @Test("Generates markdown with removed rules")
    func testGeneratesMarkdownWithRemovedRules() async {
        let generator = PRCommentGenerator()
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: [],
            removedRules: ["deprecated_rule"],
            modifiedRules: [],
            before: "",
            after: ""
        )
        let markdown = generator.generateMarkdown(from: diff)

        #expect(markdown.contains("### Rules Removed (1)"))
        #expect(markdown.contains("`deprecated_rule`"))
    }

    @Test("Generates markdown with modified rules")
    func testGeneratesMarkdownWithModifiedRules() async {
        let generator = PRCommentGenerator()
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: [],
            removedRules: [],
            modifiedRules: ["force_cast"],
            before: "",
            after: ""
        )
        let markdown = generator.generateMarkdown(from: diff)

        #expect(markdown.contains("### Rules Modified (1)"))
        #expect(markdown.contains("`force_cast`"))
    }

    @Test("Generates markdown with all change types")
    func testGeneratesMarkdownWithAllChangeTypes() async {
        let generator = PRCommentGenerator()
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: ["new_rule"],
            removedRules: ["old_rule"],
            modifiedRules: ["changed_rule"],
            before: "",
            after: ""
        )
        let markdown = generator.generateMarkdown(from: diff)

        #expect(markdown.contains("### Summary"))
        #expect(markdown.contains("**1** rule(s) added"))
        #expect(markdown.contains("**1** rule(s) removed"))
        #expect(markdown.contains("**1** rule(s) modified"))
        #expect(markdown.contains("### Rules Added"))
        #expect(markdown.contains("### Rules Removed"))
        #expect(markdown.contains("### Rules Modified"))
    }

    @Test("Handles empty diff correctly")
    func testHandlesEmptyDiff() async {
        let generator = PRCommentGenerator()
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: [],
            removedRules: [],
            modifiedRules: [],
            before: "",
            after: ""
        )
        let markdown = generator.generateMarkdown(from: diff)

        #expect(markdown.contains("No changes to SwiftLint configuration"))
        #expect(!markdown.contains("### Rules Added"))
        #expect(!markdown.contains("### Rules Removed"))
        #expect(!markdown.contains("### Rules Modified"))
    }

    // MARK: - Options Tests

    @Test("Respects includeHeader option")
    func testRespectsIncludeHeaderOption() async {
        let generator = PRCommentGenerator()
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: ["rule"],
            removedRules: [],
            modifiedRules: [],
            before: "",
            after: ""
        )

        let withHeader = generator.generateMarkdown(
            from: diff,
            options: PRCommentOptions(includeHeader: true)
        )
        let withoutHeader = generator.generateMarkdown(
            from: diff,
            options: PRCommentOptions(includeHeader: false)
        )

        #expect(withHeader.contains("## SwiftLint Configuration Changes"))
        #expect(!withoutHeader.contains("## SwiftLint Configuration Changes"))
    }

    @Test("Respects includeFooter option")
    func testRespectsIncludeFooterOption() async {
        let generator = PRCommentGenerator()
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: ["rule"],
            removedRules: [],
            modifiedRules: [],
            before: "",
            after: ""
        )

        let withFooter = generator.generateMarkdown(
            from: diff,
            options: PRCommentOptions(includeFooter: true)
        )
        let withoutFooter = generator.generateMarkdown(
            from: diff,
            options: PRCommentOptions(includeFooter: false)
        )

        #expect(withFooter.contains("Generated by SwiftLint Rule Studio"))
        #expect(!withoutFooter.contains("Generated by SwiftLint Rule Studio"))
    }

    @Test("Respects includeRuleLinks option")
    func testRespectsIncludeRuleLinksOption() async {
        let generator = PRCommentGenerator()
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: ["force_cast"],
            removedRules: [],
            modifiedRules: [],
            before: "",
            after: ""
        )

        let withLinks = generator.generateMarkdown(
            from: diff,
            options: PRCommentOptions(includeRuleLinks: true)
        )
        let withoutLinks = generator.generateMarkdown(
            from: diff,
            options: PRCommentOptions(includeRuleLinks: false)
        )

        #expect(withLinks.contains("](https://realm.github.io/SwiftLint/force_cast.html)"))
        #expect(!withoutLinks.contains("](https://"))
    }

    @Test("Respects includeDiffSummary option")
    func testRespectsIncludeDiffSummaryOption() async {
        let generator = PRCommentGenerator()
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: ["rule"],
            removedRules: [],
            modifiedRules: [],
            before: "",
            after: ""
        )

        let withSummary = generator.generateMarkdown(
            from: diff,
            options: PRCommentOptions(includeDiffSummary: true)
        )
        let withoutSummary = generator.generateMarkdown(
            from: diff,
            options: PRCommentOptions(includeDiffSummary: false)
        )

        #expect(withSummary.contains("### Summary"))
        #expect(!withoutSummary.contains("### Summary"))
    }

    @Test("Respects customTitle option")
    func testRespectsCustomTitleOption() async {
        let generator = PRCommentGenerator()
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: ["rule"],
            removedRules: [],
            modifiedRules: [],
            before: "",
            after: ""
        )
        let markdown = generator.generateMarkdown(
            from: diff,
            options: PRCommentOptions(customTitle: "Custom Title Here")
        )

        #expect(markdown.contains("## Custom Title Here"))
        #expect(!markdown.contains("## SwiftLint Configuration Changes"))
    }

    @Test("Minimal options produce compact output")
    func testMinimalOptionsProduceCompactOutput() async {
        let generator = PRCommentGenerator()
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: ["rule"],
            removedRules: [],
            modifiedRules: [],
            before: "",
            after: ""
        )
        let markdown = generator.generateMarkdown(from: diff, options: .minimal)

        #expect(!markdown.contains("## SwiftLint"))
        #expect(!markdown.contains("### Summary"))
        #expect(!markdown.contains("Generated by"))
        #expect(!markdown.contains("](https://"))
        #expect(markdown.contains("`rule`"))
    }

    // MARK: - Sorting Tests

    @Test("Rules are sorted alphabetically")
    func testRulesAreSortedAlphabetically() async {
        let generator = PRCommentGenerator()
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: ["zebra_rule", "alpha_rule", "middle_rule"],
            removedRules: [],
            modifiedRules: [],
            before: "",
            after: ""
        )
        let markdown = generator.generateMarkdown(from: diff)

        // Check order by finding positions
        let alphaPos = markdown.range(of: "alpha_rule")?.lowerBound
        let middlePos = markdown.range(of: "middle_rule")?.lowerBound
        let zebraPos = markdown.range(of: "zebra_rule")?.lowerBound

        #expect(alphaPos != nil)
        #expect(middlePos != nil)
        #expect(zebraPos != nil)

        if let a = alphaPos, let m = middlePos, let z = zebraPos {
            #expect(a < m)
            #expect(m < z)
        }
    }

    // MARK: - Extension Tests

    @Test("ConfigDiff extension generates markdown")
    func testConfigDiffExtension() async {
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: ["test_rule"],
            removedRules: [],
            modifiedRules: [],
            before: "",
            after: ""
        )
        let markdown = diff.toMarkdown()

        #expect(markdown.contains("`test_rule`"))
        #expect(markdown.contains("## SwiftLint Configuration Changes"))
    }

    @Test("ConfigDiff extension respects options")
    func testConfigDiffExtensionWithOptions() async {
        let diff = YAMLConfigurationEngine.ConfigDiff(
            addedRules: ["test_rule"],
            removedRules: [],
            modifiedRules: [],
            before: "",
            after: ""
        )
        let markdown = diff.toMarkdown(options: .minimal)

        #expect(markdown.contains("`test_rule`"))
        #expect(!markdown.contains("## SwiftLint Configuration Changes"))
    }

    // MARK: - PRCommentOptions Tests

    @Test("Default options have expected values")
    func testDefaultOptions() {
        let options = PRCommentOptions.default

        #expect(options.includeHeader)
        #expect(options.includeFooter)
        #expect(options.includeRuleLinks)
        #expect(options.includeDiffSummary)
        #expect(options.customTitle == nil)
    }

    @Test("Minimal options have expected values")
    func testMinimalOptions() {
        let options = PRCommentOptions.minimal

        #expect(!options.includeHeader)
        #expect(!options.includeFooter)
        #expect(!options.includeRuleLinks)
        #expect(!options.includeDiffSummary)
        #expect(options.customTitle == nil)
    }
}
